version: '2'
services:
  hello-gopher:
    build: ./src
    command: go run main.go
    volumes:
      - ./src:/go/src/app
    working_dir: /go/src/app
    ports:
      - "3001:3001"
    environment:
      PORT: 3001